  name: CI/CD Pipeline

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'

        - name: Build with Maven
          run: mvn -B clean package --file pom.xml

        - name: Run tests
          run: mvn test

        - name: SonarCloud Scan
          uses: SonarSource/sonarqube-scan-action@v5.0.0
          with:
            args: >
              -Dsonar.projectKey=BrunoCastro13_Asseco-Challenge
              -Dsonar.organization=brunocastro13
              -Dsonar.sources=src/main/java
              -Dsonar.tests=src/test/java
              -Dsonar.java.binaries=target/classes
              -Dsonar.java.test.binaries=target/test-classes
              -Dsonar.junit.reportPaths=target/surefire-reports
              -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
              -Dsonar.sourceEncoding=UTF-8
              -Dsonar.verbose=true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: https://sonarcloud.io

        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: |
              brunocast13/Asseco-challenge:latest

    deploy:
      needs: build
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/main'

      steps:
        - uses: actions/checkout@v3

        - name: Deploy to Production (Simulation)
          run: |
            echo "Deploying to production..."
            echo "Application deployed successfully!"
